version: '3'
services:
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  web:
    build: ./
    user: root
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true
    depends_on:
      - db
    